### ISSUE TITLE
Apply new template to specification pages (Tracking issue)

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/specifications#541]
# Instructions
1. Check the "Started" checkbox when you start working with a specification
2. Adjust the specification page to follow the [template](https://raw.githubusercontent.com/jakartaee/specification-committee/master/spec_page_template.md)
   a. Reach out to the project team for the specification if clarifications are needed
4. Create a PR
   a. Notify the project team of the changes and ask them to check out the PR (can be skipped if the changes are trivial)
6. Check the checkbox for the specification when the PR has been merged

_Focus on the latest version of each specification_

- [ ] Jakarta EE Platform
  - [ ]  Started
- [ ] Jakarta EE Web Profile
  - [ ]  Started
- [ ] Jakarta EE Core Profile
  - [ ]  Started
- [ ] Activation
  - [ ]  Started
- [ ] Annotations
  - [ ]  Started
- [ ] Authentication
  - [ ]  Started
- [ ] Authorization
  - [ ]  Started
- [ ] Batch
  - [ ]  Started
- [ ] Bean Validation
  - [ ]  Started
- [ ] Concurrency
  - [ ]  Started
- [ ] Connectors
  - [ ]  Started
- [ ] CDI
  - [ ]  Started
- [ ] Debugging Support for Other Languages
  - [ ]  Started
- [ ] Dependency Injection
  - [ ]  Started
- [ ] Deployment
  - [ ]  Started
- [ ] Enterprise Beans
  - [ ]  Started
- [ ] Enterprise Web Services
  - [ ]  Started
- [ ] Expression Language
  - [ ]  Started
- [ ] Faces
  - [ ]  Started
- [ ] Interceptors
  - [ ]  Started
- [ ] JSON Binding
  - [ ]  Started
- [ ] JSON Processing
  - [ ]  Started
- [ ] Mail
  - [ ]  Started
- [ ] Managed Beans
  - [ ]  Started
- [ ] Management
  - [ ]  Started
- [ ] Messaging
  - [ ]  Started
- [ ] MVC
  - [ ]  Started
- [ ] NoSQL
  - [ ]  Started
- [ ] Persistence
  - [ ]  Started
- [ ] RESTful Web Services
  - [ ]  Started
- [ ] Security
  - [ ]  Started
- [ ] Server Pages
  - [ ]  Started
- [ ] Servlet
  - [ ]  Started
- [ ] SOAP with Attachments
  - [ ]  Started
- [ ] Standard Tag Library
  - [ ]  Started
- [ ] Transactions
  - [ ]  Started
- [ ] Web Services Metadata
  - [ ]  Started
- [ ] WebSocket
  - [ ]  Started
- [ ] XML Binding
  - [ ]  Started
- [ ] XML Registries
  - [ ]  Started
- [ ] XML RPC
  - [ ]  Started
- [ ] XML Web Services
  - [ ]  Started
